import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import reportService from '../../services/reportService';
import { useAuth } from '../../context/AuthContext';

const formatDate = (iso) => {
    if (!iso) return '—';
    return new Date(iso).toLocaleDateString('en-US', {
        month: 'short', day: 'numeric', year: 'numeric',
        hour: '2-digit', minute: '2-digit',
    });
};

const STATUS_COLORS = {
    draft:     'bg-gray-100 text-gray-600',
    generated: 'bg-blue-100 text-blue-700',
    approved:  'bg-green-100 text-green-700',
};

export default function ReportPreview() {
    const { reportId } = useParams();
    const navigate = useNavigate();
    const { role } = useAuth();

    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    // approval panel state
    const [showApprovalPanel, setShowApprovalPanel] = useState(false);
    const [approvalNotes, setApprovalNotes] = useState('');
    const [approving, setApproving] = useState(false);

    const [downloading, setDownloading] = useState(false);

    useEffect(() => {
        const load = async () => {
            try {
                setLoading(true);
                const data = await reportService.getReportById(reportId);
                setReport(data);
            } catch (err) {
                console.error('ReportPreview.load:', err);
                setError('Failed to load report. It may have been deleted or you may not have access.');
            } finally {
                setLoading(false);
            }
        };
        load();
    }, [reportId]);

    const handleApprove = async () => {
        try {
            setApproving(true);
            const updated = await reportService.approveReport(reportId, approvalNotes);
            setReport(updated);
            setShowApprovalPanel(false);
            setApprovalNotes('');
            toast.success('Report approved successfully');
        } catch (err) {
            console.error('ReportPreview.handleApprove:', err);
            toast.error(err.response?.data?.error || 'Failed to approve report');
        } finally {
            setApproving(false);
        }
    };

    const handleDownloadPdf = async () => {
        setDownloading(true);
        try {
            const filename = `${report.title.replace(/\s+/g, '_')}.pdf`;
            await reportService.downloadPdf(report.id, filename);
        } catch (err) {
            toast.error('Failed to download PDF');
        } finally {
            setDownloading(false);
        }
    };

    const handleDownloadJson = () => {
        try {
            reportService.downloadJson(report);
        } catch (err) {
            toast.error('Failed to download JSON');
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-96 text-gray-400 text-sm">
                Loading report...
            </div>
        );
    }

    if (error || !report) {
        return (
            <div className="flex flex-col items-center justify-center h-96 gap-3">
                <p className="text-red-500 text-sm">{error || 'Report not found'}</p>
                <button
                    onClick={() => navigate(-1)}
                    className="text-sm text-emerald-600 underline"
                >
                    Go back
                </button>
            </div>
        );
    }

    const canApprove = role !== 'viewer' && report.status === 'generated';

    return (
        <div className="max-w-6xl mx-auto px-6 py-8">

            {/* Back */}
            <button
                onClick={() => navigate(-1)}
                className="text-sm text-gray-500 hover:text-gray-700 mb-4 flex items-center gap-1"
            >
                ← Back to Reports
            </button>

            {/* Title row */}
            <div className="flex items-start justify-between mb-6 gap-4 flex-wrap">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900">{report.title}</h1>
                    <div className="flex items-center gap-3 mt-2 text-sm text-gray-500 flex-wrap">
                        <span>Generated by {report.generated_by_name || '—'}</span>
                        <span>•</span>
                        <span>{formatDate(report.generated_at)}</span>
                    </div>
                </div>
                <span className={`px-3 py-1 rounded-full text-sm font-medium flex-shrink-0 ${STATUS_COLORS[report.status]}`}>
                    {report.status}
                </span>
            </div>

            {/* Action buttons */}
            <div className="flex gap-3 mb-6 flex-wrap">
                {report.status !== 'draft' && (
                    <button
                        onClick={handleDownloadPdf}
                        disabled={downloading}
                        className="px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 disabled:opacity-50 transition-colors"
                    >
                        {downloading ? 'Downloading...' : 'Download PDF'}
                    </button>
                )}
                <button
                    onClick={handleDownloadJson}
                    className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
                >
                    Download JSON
                </button>
                {canApprove && !showApprovalPanel && (
                    <button
                        onClick={() => setShowApprovalPanel(true)}
                        className="px-4 py-2 border border-emerald-300 text-emerald-700 rounded-lg hover:bg-emerald-50 transition-colors"
                    >
                        Approve Report
                    </button>
                )}
            </div>

            {/* Approval panel */}
            {showApprovalPanel && canApprove && (
                <div className="mb-6 p-4 bg-emerald-50 border border-emerald-200 rounded-lg">
                    <h3 className="text-sm font-semibold text-gray-800 mb-2">Confirm Approval</h3>
                    <label className="block text-sm text-gray-700 mb-1">
                        Notes <span className="text-gray-400">(optional)</span>
                    </label>
                    <textarea
                        value={approvalNotes}
                        onChange={(e) => setApprovalNotes(e.target.value)}
                        placeholder="Add any notes about this approval..."
                        rows={3}
                        className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                    <div className="flex gap-2 mt-3">
                        <button
                            onClick={handleApprove}
                            disabled={approving}
                            className="px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 disabled:opacity-50 transition-colors"
                        >
                            {approving ? 'Approving...' : 'Confirm Approval'}
                        </button>
                        <button
                            onClick={() => { setShowApprovalPanel(false); setApprovalNotes(''); }}
                            className="px-4 py-2 text-gray-600 hover:text-gray-900"
                        >
                            Cancel
                        </button>
                    </div>
                </div>
            )}

            {/* Approved banner */}
            {report.status === 'approved' && report.approved_by_name && (
                <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-lg">
                    <p className="text-sm text-green-700 font-medium">
                        ✓ Approved by {report.approved_by_name} on {formatDate(report.approved_at)}
                    </p>
                    {report.approval_notes && (
                        <p className="text-sm text-gray-600 mt-1">Notes: {report.approval_notes}</p>
                    )}
                </div>
            )}

            {/* Report body */}
            <div className="bg-white border rounded-xl p-6">
                {report.report_type === 'vendor_risk'         && <VendorRiskContent data={report.data} />}
                {report.report_type === 'compliance_summary'  && <ComplianceSummaryContent data={report.data} />}
                {report.report_type === 'emissions_overview'  && <EmissionsOverviewContent data={report.data} />}
                {report.report_type === 'document_audit'      && <DocumentAuditContent data={report.data} />}
            </div>
        </div>
    );
}


/* ============================================================
   Report content components — one per report_type
   ============================================================ */

function VendorRiskContent({ data }) {
    const rs = data.risk_summary || {};
    const em = data.emissions || {};
    const docs = data.documents || {};
    const recs = data.recommendations || [];

    return (
        <div className="space-y-8">
            <Section title="Risk Summary">
                <StatGrid items={[
                    { label: 'Overall Risk Score', value: `${rs.overall_score || 0} / 100` },
                    { label: 'Risk Level', value: (rs.risk_level || '—').toUpperCase() },
                    { label: 'Compliance Status', value: data.vendor?.compliance_status || '—' },
                ]} />
                {rs.factors?.length > 0 && (
                    <div className="mt-4">
                        <p className="text-sm font-medium text-gray-700 mb-2">Risk Factors</p>
                        {rs.factors.map((f, i) => (
                            <p key={i} className="text-sm text-gray-600">• {f.name} — {f.impact}</p>
                        ))}
                    </div>
                )}
            </Section>

            <Section title="Emissions Data">
                <StatGrid items={[
                    { label: 'Total CO₂', value: `${(em.total_co2 || 0).toLocaleString()} ${em.unit || 'tonnes'}` },
                    { label: 'Exceeds Threshold', value: em.exceeds_threshold ? 'Yes' : 'No' },
                ]} />
            </Section>

            <Section title="Document Status">
                <StatGrid items={[
                    { label: 'Total',          value: docs.total || 0 },
                    { label: 'Valid',          value: docs.valid || 0 },
                    { label: 'Flagged',        value: docs.flagged || 0 },
                    { label: 'Expired',        value: docs.expired || 0 },
                    { label: 'Avg Confidence', value: `${docs.avg_confidence || 0}%` },
                ]} />
            </Section>

            {recs.length > 0 && (
                <Section title="Recommendations">
                    <ul className="space-y-1">
                        {recs.map((r, i) => (
                            <li key={i} className="text-sm text-gray-700 flex gap-2">
                                <span className="text-emerald-500 flex-shrink-0">•</span>
                                {r}
                            </li>
                        ))}
                    </ul>
                </Section>
            )}
        </div>
    );
}

function ComplianceSummaryContent({ data }) {
    const s = data.summary || {};
    const vendors = data.vendors || [];

    return (
        <div className="space-y-8">
            <Section title="Organisation Summary">
                <StatGrid items={[
                    { label: 'Total Vendors',       value: s.total_vendors || 0 },
                    { label: 'Compliant',           value: s.compliant || 0 },
                    { label: 'Non-Compliant',       value: s.non_compliant || 0 },
                    { label: 'Pending',             value: s.pending || 0 },
                    { label: 'Expired',             value: s.expired || 0 },
                    { label: 'High / Critical Risk', value: s.high_risk || 0 },
                ]} />
            </Section>

            {vendors.length > 0 && (
                <Section title="Vendor Status">
                    <DataTable
                        headers={['Vendor', 'Industry', 'Compliance', 'Risk Level']}
                        rows={vendors.slice(0, 30).map((v) => [
                            v.name,
                            v.industry || '—',
                            <StatusPill key={v.vendor_id} value={v.compliance_status} />,
                            <StatusPill key={v.vendor_id + '_r'} value={v.risk_level} />,
                        ])}
                    />
                </Section>
            )}
        </div>
    );
}

function EmissionsOverviewContent({ data }) {
    const s = data.summary || {};
    const topEmitters = data.vendor_emissions || [];
    const byIndustry = data.by_industry || [];

    return (
        <div className="space-y-8">
            <Section title="Emissions Summary">
                <StatGrid items={[
                    { label: 'Vendors with Data', value: s.total_vendors_with_data || 0 },
                    { label: 'Total Emissions', value: `${(s.total_emissions || 0).toLocaleString()} ${s.unit || 'tonnes CO2e'}` },
                ]} />
            </Section>

            {topEmitters.length > 0 && (
                <Section title="Top Emitters">
                    <DataTable
                        headers={['Rank', 'Vendor', 'Industry', 'CO₂ (tonnes)', 'Risk']}
                        rows={topEmitters.slice(0, 15).map((v, i) => [
                            i + 1,
                            v.vendor_name,
                            v.industry || '—',
                            v.total_co2.toLocaleString(),
                            <StatusPill key={v.vendor_id} value={v.risk_level} />,
                        ])}
                    />
                </Section>
            )}

            {byIndustry.length > 0 && (
                <Section title="By Industry">
                    <DataTable
                        headers={['Industry', 'Total CO₂ (tonnes)', 'Vendors']}
                        rows={byIndustry.map((row) => [
                            row.industry,
                            row.total_co2.toLocaleString(),
                            row.vendor_count,
                        ])}
                    />
                </Section>
            )}
        </div>
    );
}

function DocumentAuditContent({ data }) {
    const vs = data.validation_summary || {};
    const qm = data.quality_metrics || {};
    const vendorSummaries = data.vendor_summaries || [];

    return (
        <div className="space-y-8">
            <Section title="Validation Summary">
                <StatGrid items={[
                    { label: 'Total Validations',  value: vs.total_validations || 0 },
                    { label: 'Completed',          value: vs.completed || 0 },
                    { label: 'Auto-Approved',      value: vs.auto_approved || 0 },
                    { label: 'Flagged for Review', value: vs.flagged_for_review || 0 },
                    { label: 'Auto-Approval Rate', value: `${vs.auto_approval_rate || 0}%` },
                    { label: 'Failed',             value: vs.failed || 0 },
                ]} />
            </Section>

            <Section title="Quality Metrics">
                <StatGrid items={[
                    { label: 'Avg Overall Confidence', value: `${qm.avg_overall_confidence || 0}%` },
                    { label: 'Avg Readability Score',  value: `${qm.avg_readability_score || 0}%` },
                    { label: 'Avg Relevance Score',    value: `${qm.avg_relevance_score || 0}%` },
                    { label: 'Avg Authenticity Score', value: `${qm.avg_authenticity_score || 0}%` },
                ]} />
            </Section>

            {vendorSummaries.length > 0 && (
                <Section title="Per-Vendor Summary">
                    <DataTable
                        headers={['Vendor', 'Validations', 'Flagged', 'Avg Confidence']}
                        rows={vendorSummaries.slice(0, 25).map((v) => [
                            v.vendor_name,
                            v.total_validations,
                            v.flagged,
                            `${v.avg_confidence}%`,
                        ])}
                    />
                </Section>
            )}
        </div>
    );
}


/* ============================================================
   Shared layout helpers
   ============================================================ */

function Section({ title, children }) {
    return (
        <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-4 pb-2 border-b border-gray-100">
                {title}
            </h2>
            {children}
        </div>
    );
}

function StatGrid({ items }) {
    return (
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            {items.map(({ label, value }) => (
                <div key={label} className="bg-gray-50 rounded-lg p-3">
                    <p className="text-xs text-gray-500 uppercase font-medium mb-1">{label}</p>
                    <p className="text-lg font-semibold text-gray-900">{value}</p>
                </div>
            ))}
        </div>
    );
}

function DataTable({ headers, rows }) {
    if (!rows.length) return null;

    return (
        <div className="overflow-x-auto">
            <table className="w-full text-sm">
                <thead className="bg-gray-50">
                    <tr>
                        {headers.map((h) => (
                            <th key={h} className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase">
                                {h}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                    {rows.map((row, i) => (
                        <tr key={i} className="hover:bg-gray-50">
                            {row.map((cell, j) => (
                                <td key={j} className="px-4 py-2.5 text-gray-700">
                                    {cell}
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
}

// small inline badge for compliance_status / risk_level values
function StatusPill({ value }) {
    const colors = {
        compliant:     'bg-green-100 text-green-700',
        non_compliant: 'bg-red-100 text-red-700',
        pending:       'bg-yellow-100 text-yellow-700',
        expired:       'bg-gray-100 text-gray-600',
        low:           'bg-green-100 text-green-700',
        medium:        'bg-yellow-100 text-yellow-700',
        high:          'bg-orange-100 text-orange-700',
        critical:      'bg-red-100 text-red-700',
        unknown:       'bg-gray-100 text-gray-500',
    };
    return (
        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${colors[value] || 'bg-gray-100 text-gray-600'}`}>
            {value}
        </span>
    );
}